services:
  db:
    container_name: postgres1
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 23099
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin1
    image: elestio/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "nbavsunovsky@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: 23099
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "5050:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
